"""User id to bigint

Revision ID: 4fac9d728f4a
Revises: 248e28c2a024
Create Date: 2024-12-25 00:44:06.580353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fac9d728f4a"
down_revision: Union[str, None] = "248e28c2a024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("covers", "author_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('users_id_seq'::regclass)"),
    )
    op.alter_column("covers", "author_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True)
    # ### end Alembic commands ###
