name: Bot

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.10", "3.11", "3.12"]

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt
          pip install -r requirements/lint.txt
          pip install -r requirements/dev.txt

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
           python-version: 3.12
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/lint.txt
      - name: flake8
        run: |
          flake8 --verbose
      - name: black
        run: |
          black --check --config pyproject.toml .
